#!/bin/bash
DF='\e[39m'
RED='\033[0;31m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lyellow='\e[93m'
Lgreen='\e[92m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m$NC"
# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/KhaiVpn767/izinsc/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $useexp == "lifetime" || $useexp == "Lifetime" ]]; then
echo -ne
else
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            \033[91;1mPERMISSION DENIED !\033[0m"
    echo -e "   \033[0;33mYour VPS\033[0m $ipsaya \033[0;33mHas been Banned\033[0m"
    echo -e "     \033[0;33mBuy access permissions for scripts\033[0m"
    echo -e "             \033[0;33mContact Admin :\033[0m"
    echo -e "      \033[2;32mWhatsApp\033[0m wa.me/6285935195701"
	echo -e "      \033[2;32mTelegram\033[0m t.me/xdxl_real"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
fi
}
checking_sc

function install() {
clear
NS=$( cat /etc/xray/dns )
PUB=$( cat /etc/slowdns/server.pub )
domain=$(cat /etc/xray/domain)
#color
grenbo="\e[92;1m"
NC='\e[0m'
#install


cd /etc/systemd/system/
rm -rf xdbot.service &>/dev/null
cd
find /usr/bin/ -name "*.session*" -delete
rm -rf /usr/bin/xdxl/var.txt &>/dev/null
rm -rf /usr/bin/xdxl/database.db &>/dev/null
apt update
apt install python3 python3-pip git
cd /usr/bin
wget -q -O bot.zip "https://raw.githubusercontent.com/KhaiVpn767/V6/main/bot/bot.zip"
unzip bot.zip
mv bot/* /usr/bin
chmod +x /usr/bin/*
rm -rf bot.zip
clear
wget -q -O xdxl.zip "https://raw.githubusercontent.com/KhaiVpn767/V6/main/bot/xdxl.zip"
unzip xdxl.zip

function cekos() {
source /etc/os-release
echo "$ID $VERSION_ID"
}

if [[ $(cekos) == "ubuntu 22.04" ]]; then
pip3 install -r xdxl/requirements.txt
else
pip3 install -r xdxl/requirements.txt --break-system-packages
fi

clear
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e " \e[1;97;101m              INSTALL BOT              \e[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "${grenbo}Tutorial Creat Bot and ID Telegram${NC}"
echo -e "${grenbo}[*] Creat Bot and Token Bot : @BotFather${NC}"
echo -e "${grenbo}[*] Info Id Telegram : @MissRose_bot , perintah /info${NC}"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
function token_input() {
read -p "[*] Input your Bot Token : " bottoken
if [[ -z $bottoken ]]; then token_input ;fi
}
function id_input() {
read -p "[*] Input Your Id Telegram : " admin
if [[ -z $admin ]]; then id_input ;fi
}
token_input
id_input

echo -e BOT_TOKEN='"'$bottoken'"' >> /usr/bin/xdxl/var.txt
echo -e ADMIN='"'$admin'"' >> /usr/bin/xdxl/var.txt
echo -e DOMAIN='"'$domain'"' >> /usr/bin/xdxl/var.txt
echo -e PUB='"'$PUB'"' >> /usr/bin/xdxl/var.txt
echo -e HOST='"'$NS'"' >> /usr/bin/xdxl/var.txt
clear

cat > /etc/systemd/system/xdbot.service << END
[Unit]
Description=Simple XD BotzZ - @xdxl_real
After=network.target

[Service]
WorkingDirectory=/usr/bin
ExecStart=/usr/bin/python3 -m xdxl
Restart=always

[Install]
WantedBy=multi-user.target
END

systemctl start xdbot 
systemctl enable xdbot
systemctl restart xdbot
cd /root
echo "Done"
echo "Your Data Bot"
echo -e "==============================="
echo "Token Bot         : $bottoken"
echo "Admin          : $admin"
echo "Domain        : $domain"
echo -e "==============================="
echo "Setting done"
echo
echo " Installations complete, type /menu on your bot"
}

if [[ "$(systemctl is-active xdbot)" == "active" ]]; then 
   status_bot="${GREEN}ON${NC}"
else
   status_bot="${red}OFF${NC}"
fi

clear 
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "         • MENU BOT PANEL •         "
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "" 
echo -e " ${KIRI} Status Bot ( ${status_bot} )"
echo -e ""
echo -e " [\e[36m•1\e[0m] Add Bot Panel"
echo -e " [\e[36m•2\e[0m] Delete Bot Panel"
echo -e " [\e[36m•3\e[0m] Stop Bot Panel"
echo -e " [\e[36m•4\e[0m] Restart Bot Panel"
echo -e "" 
echo -e " [\e[31m•0\e[0m] \e[31mBack To Menu\033[0m"
echo -e "" 
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
read -p " Select menu :  "  opt
echo -e   ""
case $opt in
01 | 1) clear ; install ;;
02 | 2) clear ; hapus-bot ;;
02 | 3) clear ; stop-bot ;;
00 | 4) clear ; restart-bot ;;
*) clear ; menu ;;
esac